<MyWidget>:
    cols: 2
    padding: 10
    spacing: 5
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        text: "Управление"
        font_size: 50

        color: 0,0,0,0


    Button:
        text: "test1"
        font_size: 30
    Button:
        text: "test2"
        font_size: 30
    Button:
        text: "test3"
        font_size: 30